export const imgApp = {
    logoApp: require('../img/logoApp.png'),
    userDefault: require('../img/userDefault.png'),
    imgHeart: require('../img/iconHeart.png'),
    imgMap: require('../img/iconMap.png'),
    camera: require('../img/camera.png'),
    picture: require('../img/picture.png'),
    banner: require('../img/banner.jpg'),
    imgDemo: require('../img/imgDemo.png'),
    iconStar: require('../img/star.png'),
    iconDiscount: require('../img/discount.png'),
    iconTable: require('../img/iconTable.png'),
    iconDelivery: require('../img/iconDelivery.png'),
    boxNothing: require('../img/boxNothing.png'),
    imgWhite: require('../img/imgWhite.png'),
    shop1: require('../img/shop1.jpg'),
    shop2: require('../img/shop2.jpg'),
    shop3: require('../img/shop3.jpg'),
}