// import auth from '@react-native-firebase/auth';
// import { GoogleReCaptchaProvider } from 'react-native-google-recaptcha';
// import { View,TextInput,Button } from 'react-native';

// function App() {
//   const [phoneNumber, setPhoneNumber] = useState('');
//   const [verificationId, setVerificationId] = useState('');
//   const [verificationCode, setVerificationCode] = useState('');

//   const handleSendCode = async () => {
//     const phoneProvider = new auth.PhoneAuthProvider();
//     const verificationId = await phoneProvider.verifyPhoneNumber(
//       phoneNumber,
//       // This is the reCAPTCHA token generated by the user's response to the reCAPTCHA challenge.
//       // You can obtain this token using the `onVerify` callback provided by `react-native-google-recaptcha`.
//       recaptchaToken,
//     );
//     setVerificationId(verificationId);
//   };

//   const handleVerifyCode = async () => {
//     const credential = auth.PhoneAuthProvider.credential(
//       verificationId,
//       verificationCode,
//     );
//     await auth().signInWithCredential(credential);
//   };

//   return (
//     <GoogleReCaptchaProvider
//       reCaptchaSiteKey="your_site_key"
//       onVerify={(token) => {
//         // This callback is called when the user successfully completes the reCAPTCHA challenge.
//         // You can use the `token` parameter to verify the user's response on your server.
//         console.log('reCAPTCHA token:', token);
//       }}
//     >
//       <View>
//         <TextInput
//           placeholder="Enter your phone number"
//           value={phoneNumber}
//           onChangeText={setPhoneNumber}
//         />
//         <Button title="Send verification code" onPress={handleSendCode} />
//         <TextInput
//           placeholder="Enter verification code"
//           value={verificationCode}
//           onChangeText={setVerificationCode}
//         />
//         <Button title="Verify code" onPress={handleVerifyCode} />
//       </View>
//     </GoogleReCaptchaProvider>
//   );
// }
